- name: Check if /swapfile exists
  stat:
    path: /swapfile
  register: swapfile

- name: Create swapfile if it doesn't exist
  command: fallocate -l 1G /swapfile
  when: not swapfile.stat.exists
  become: yes

- name: Set permissions on swapfile
  file:
    path: /swapfile
    owner: root
    group: root
    mode: '0600'
  when: not swapfile.stat.exists
  become: yes

- name: Make swap
  command: mkswap /swapfile
  when: not swapfile.stat.exists
  become: yes

- name: Enable swap
  command: swapon /swapfile
  register: swapon_result
  failed_when: swapon_result.rc not in [0, 255]  # rc 255 if already active
  changed_when: swapon_result.rc == 0
  become: yes

- name: Ensure swap entry in /etc/fstab
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present
  become: yes


# Step 1: Install Apache
- name: Install Apache
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "httpd"
    state: present

# Step 2: Install Git
- name: Install Git
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "git"
    state: present

# Step 3: Install EPEL release
- name: Install EPEL release
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y

# Step 4: Install dnf-utils and Remi repo
- name: Install dnf-utils and Remi repository
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: sudo dnf install dnf-utils http://rpms.remirepo.net/enterprise/remi-release-9.rpm -y

# Step 5: Reset PHP module
- name: Reset PHP module
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: sudo dnf module reset php -y

# Step 6: Enable PHP 7.4 module
- name: Enable PHP 7.4 module
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: sudo dnf module enable php:remi-7.4 -y

# Step 7: Install PHP and extensions
- name: Install PHP and extensions
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.yum:
    name:
      - php
      - php-opcache
      - php-gd
      - php-curl
      - php-mysqlnd
    state: present

# Step 8: Install MySQL client
- name: Install MySQL client
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "mysql"
    state: present

# Step 9: Start PHP-FPM
- name: Start PHP-FPM service
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.service:
    name: php-fpm
    state: started

- name: Enable PHP-FPM service
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.service:
    name: php-fpm
    enabled: true

- name: Set SELinux boolean for httpd_execmem
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: sudo setsebool -P httpd_execmem 1

# Step 10: Clone the tooling website
- name: Clone a repo
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.git:
    repo: https://github.com/dimani001/tooling.git
    dest: /var/www/html
    force: yes

- name: Copy HTML content to one level up
  remote_user: ec2-user
  become: true
  become_user: root
  command: cp -r /var/www/html/html/ /var/www/

- name: Start httpd service, if not started
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.service:
    name: httpd
    state: started

- name: Recursively remove /var/www/html/html directory
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent

