---
- name: Include dynamic variables for all hosts
  hosts: all
  become: yes
  tasks:
    - include_vars: ../dynamic-assignments/env-vars/uat.yml
      tags:
        - always

- import_playbook: ../static-assignments/uat-webservers.yml
- import_playbook: ../static-assignments/db-servers.yml
- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required

